spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist
    username: postgres
    password: NOVIANTO

  sql:
    init:
      mode: always
      continue-on-error: false
#      data-location: classpath:demo_data.sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      root: INFO
      org:
        springframework:
          web: DEBUG
          security: DEBUG

security:
  jwt:
    secret: T0lVVDk4N3JGVEc3RlJ5ckY4Njd5ZnI4NjRSNnlEOEU=
    access: 3600000
    refresh: 2592000000